#!/usr/bin/env bash
# setup.sh — Detect hardware, generate .env, start the stack.
# Usage:
#   ./infra/scripts/setup.sh                                # interactive
#   ./infra/scripts/setup.sh /mnt/nas/soccer /mnt/nas/out   # non-interactive
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$INFRA_DIR/.." && pwd)"
ENV_FILE="$INFRA_DIR/.env"
COMPOSE_BASE="$INFRA_DIR/docker-compose.yml"
COMPOSE_GPU="$INFRA_DIR/docker-compose.gpu.yml"
COMPOSE_CMD=""

echo "=== Soccer Video Pipeline — Setup ==="
echo ""

# ── 1. Prerequisites ────────────────────────────────────────────────────────

for cmd in docker; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "FATAL: '$cmd' not found. Install Docker first."
        exit 1
    fi
done

# Detect docker compose variant
if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo "FATAL: Neither 'docker compose' nor 'docker-compose' found."
    exit 1
fi

# ── 2. NAS Paths ────────────────────────────────────────────────────────────

if [ $# -ge 2 ]; then
    NAS_MOUNT_PATH="$1"
    NAS_OUTPUT_PATH="$2"
else
    read -rp "NAS source path (read-only, where match MP4s live) [/mnt/nas/soccer]: " NAS_MOUNT_PATH
    NAS_MOUNT_PATH="${NAS_MOUNT_PATH:-/mnt/nas/soccer}"
    read -rp "NAS output path (writable, for finished reels) [${NAS_MOUNT_PATH}/output]: " NAS_OUTPUT_PATH
    NAS_OUTPUT_PATH="${NAS_OUTPUT_PATH:-${NAS_MOUNT_PATH}/output}"
fi

WORKING_DIR="${3:-/tmp/soccer-pipeline}"

echo ""
echo "Paths:"
echo "  Source:  $NAS_MOUNT_PATH"
echo "  Output:  $NAS_OUTPUT_PATH"
echo "  Working: $WORKING_DIR"

# ── 3. GPU Detection ────────────────────────────────────────────────────────

GPU_COUNT=0
USE_GPU=false
USE_COMPOSE_GPU=false

if command -v nvidia-smi &>/dev/null; then
    GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | wc -l | tr -d ' ')
    if [ "$GPU_COUNT" -gt 0 ]; then
        echo ""
        echo "NVIDIA GPU(s) detected:"
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | sed 's/^/  /'

        # Check nvidia-container-toolkit
        if docker run --rm --gpus all nvidia/cuda:12.2.0-base-ubuntu22.04 nvidia-smi &>/dev/null 2>&1; then
            echo "  Docker GPU access: OK"
            USE_GPU=true
            USE_COMPOSE_GPU=true
        else
            echo ""
            echo "WARNING: NVIDIA GPUs found but Docker cannot access them."
            echo "Install the NVIDIA Container Toolkit:"
            echo "  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \\"
            echo "    | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"
            echo '  curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \'
            echo '    | sed "s#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g" \'
            echo '    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list'
            echo "  sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit"
            echo "  sudo nvidia-ctk runtime configure --runtime=docker"
            echo "  sudo systemctl restart docker"
            echo ""
            echo "Falling back to CPU for now."
            GPU_COUNT=1
        fi
    fi
fi

if [ "$USE_GPU" = "false" ]; then
    GPU_COUNT=1
    echo ""
    echo "No NVIDIA GPU detected — workers will use CPU."
fi

# ── 4. Generate .env ─────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<ENVEOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run infra/scripts/setup.sh to regenerate.

# ── Paths ────────────────────────────────────────────────────────────────────
NAS_MOUNT_PATH=$NAS_MOUNT_PATH
NAS_OUTPUT_PATH=$NAS_OUTPUT_PATH
WORKING_DIR=$WORKING_DIR

# ── Queue ────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1
REDIS_URL=redis://redis:6379/0

# ── GPU / Workers ────────────────────────────────────────────────────────────
GPU_COUNT=$GPU_COUNT
USE_GPU=$USE_GPU

# ── Detection ────────────────────────────────────────────────────────────────
YOLO_MODEL_PATH=/models/yolov8m.pt
YOLO_INFERENCE_SIZE=1280
DETECTION_FRAME_STEP=3
MIN_EVENT_CONFIDENCE=0.65
CHUNK_DURATION_SEC=30
CHUNK_OVERLAP_SEC=2.0

# ── Clip padding ─────────────────────────────────────────────────────────────
PRE_EVENT_PAD_SEC=3.0
POST_EVENT_PAD_SEC=5.0

# ── Output encoding ──────────────────────────────────────────────────────────
OUTPUT_CODEC=copy
OUTPUT_CRF=18
OUTPUT_AUDIO_CODEC=copy

# ── NAS reliability ──────────────────────────────────────────────────────────
MAX_NAS_RETRY=3
NAS_RETRY_DELAY_SEC=5.0
WATCH_POLL_INTERVAL_SEC=10.0
WATCH_STABLE_TIME_SEC=30.0
ENVEOF

echo ""
echo "Generated $ENV_FILE"

# ── 5. Ensure directories exist ─────────────────────────────────────────────

mkdir -p "$NAS_MOUNT_PATH" 2>/dev/null || true
mkdir -p "$NAS_OUTPUT_PATH" 2>/dev/null || true
mkdir -p "$WORKING_DIR" 2>/dev/null || true
mkdir -p "$INFRA_DIR/models" 2>/dev/null || true

# ── 6. Download model weights if missing ─────────────────────────────────────

if [ ! -f "$INFRA_DIR/models/yolov8m.pt" ]; then
    echo ""
    echo "Downloading YOLOv8m weights..."
    if command -v wget &>/dev/null; then
        wget -q --show-progress -O "$INFRA_DIR/models/yolov8m.pt" \
            "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8m.pt"
    elif command -v curl &>/dev/null; then
        curl -L --progress-bar -o "$INFRA_DIR/models/yolov8m.pt" \
            "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8m.pt"
    else
        echo "WARNING: Neither wget nor curl found. Download yolov8m.pt manually to $INFRA_DIR/models/"
    fi
fi

# ── 7. Start the stack ───────────────────────────────────────────────────────

echo ""
echo "Starting stack..."

COMPOSE_FILES="-f $COMPOSE_BASE"
if [ "$USE_COMPOSE_GPU" = "true" ]; then
    COMPOSE_FILES="$COMPOSE_FILES -f $COMPOSE_GPU"
    echo "  GPU mode: $GPU_COUNT worker(s) with NVIDIA GPU"
else
    echo "  CPU mode: $GPU_COUNT worker(s)"
fi

$COMPOSE_CMD $COMPOSE_FILES --env-file "$ENV_FILE" up -d --build

echo ""
echo "=== Stack is up ==="
echo "  API:     http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):8080"
echo "  Flower:  http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):5555"
echo "  Monitor: http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):8080/ui"
echo ""
echo "Submit a job:"
echo "  curl -X POST http://localhost:8080/jobs \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"nas_path\": \"match.mp4\", \"reel_types\": [\"goalkeeper\", \"highlights\"]}'"
